// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoftLicence.Server.Data;

#nullable disable

namespace SoftLicence.Server.Migrations
{
    [DbContext(typeof(LicenseDbContext))]
    [Migration("20260517144248_AddCanaryAlertSeverityAndOsVersion")]
    partial class AddCanaryAlertSeverityAndOsVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoftLicence.Server.Data.AccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorDetails")
                        .HasColumnType("text");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsProxy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Isp")
                        .HasColumnType("text");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<int>("ThreatScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientIp");

                    b.HasIndex("Timestamp");

                    b.ToTable("AccessLogs");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.AdminRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminRoles");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.BannedComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ComponentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ComponentType", "ComponentHash", "ProductId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("BannedComponents");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.BannedHardwareId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PiracySuspectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("HardwareId", "ProductId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("BannedHardwareIds");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.BannedIp", b =>
                {
                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<int>("BanCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IpAddress");

                    b.ToTable("BannedIps");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.CanaryAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OsVersion")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RepeatCount")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CanaryAlerts");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.HardwareFingerprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BiosHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CpuHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DiskHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HostHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ListType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("MotherboardHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BiosHash");

                    b.HasIndex("ClusterId");

                    b.HasIndex("CpuHash");

                    b.HasIndex("DiskHash");

                    b.HasIndex("HardwareId")
                        .IsUnique();

                    b.HasIndex("HostHash");

                    b.HasIndex("MotherboardHash");

                    b.ToTable("HardwareFingerprints");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.IpThreatScore", b =>
                {
                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastHit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("IpAddress");

                    b.ToTable("IpThreatScores");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AllowedVersions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HardwareId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LicenseTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("integer");

                    b.Property<string>("PartnerCode")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecoveryCount")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<string>("ResetCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetCodeExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ValidityDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LicenseKey")
                        .IsUnique();

                    b.HasIndex("LicenseTypeId");

                    b.HasIndex("ProductId", "HardwareId");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<string>("PerformedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.ToTable("LicenseHistories");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseRenewal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DaysAdded")
                        .HasColumnType("integer");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RenewalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("LicenseRenewals");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseSeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastCheckInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<string>("MachineName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UnlinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId", "HardwareId")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("LicenseSeats");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("DefaultAllowedVersions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DefaultDurationDays")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultMaxSeats")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxActivationsPerDay")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Slug")
                        .IsUnique();

                    b.ToTable("LicenseTypes");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseTypeCustomParam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LicenseTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LicenseTypeId", "Key")
                        .IsUnique();

                    b.ToTable("LicenseTypeCustomParams");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.PiracySuspect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("text");

                    b.Property<string>("Culture")
                        .HasColumnType("text");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DistinctIpCount")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureEvents")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddresses")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastScanAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OS")
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopEvents")
                        .HasColumnType("text");

                    b.Property<int>("TotalEvents")
                        .HasColumnType("integer");

                    b.Property<string>("Versions")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "HardwareId")
                        .IsUnique();

                    b.ToTable("PiracySuspects");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MinimumAllowedVersion")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrivateKeyXml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKeyXml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.ProductWebhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Secret")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductWebhooks");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.ResellerPartner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ResellerPartners");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.SystemSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryDiagnostic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("TelemetryRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelemetryRecordId")
                        .IsUnique();

                    b.ToTable("TelemetryDiagnostics");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryDiagnosticPort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExternalPort")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .HasColumnType("text");

                    b.Property<Guid>("TelemetryDiagnosticId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelemetryDiagnosticId");

                    b.ToTable("TelemetryDiagnosticPorts");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryDiagnosticResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("ModuleName")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TelemetryDiagnosticId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelemetryDiagnosticId");

                    b.ToTable("TelemetryDiagnosticResults");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorType")
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<Guid>("TelemetryRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelemetryRecordId")
                        .IsUnique();

                    b.ToTable("TelemetryErrors");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("text");

                    b.Property<Guid>("TelemetryRecordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TelemetryRecordId")
                        .IsUnique();

                    b.ToTable("TelemetryEvents");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientIp")
                        .HasColumnType("text");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HardwareId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Isp")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("TelemetryRecords");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.Webhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnabledEvents")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.AdminUser", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.AdminRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.BannedComponent", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.BannedHardwareId", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.CanaryAlert", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.License", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.LicenseType", "Type")
                        .WithMany("Licenses")
                        .HasForeignKey("LicenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoftLicence.Server.Data.Product", "Product")
                        .WithMany("Licenses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseHistory", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.License", "License")
                        .WithMany("History")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseRenewal", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseSeat", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.License", "License")
                        .WithMany("Seats")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("License");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseType", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.Product", "Product")
                        .WithMany("LicenseTypes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseTypeCustomParam", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.LicenseType", "LicenseType")
                        .WithMany("CustomParams")
                        .HasForeignKey("LicenseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LicenseType");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.PiracySuspect", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.Product", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.Product", "ParentProduct")
                        .WithMany("SubProducts")
                        .HasForeignKey("ParentProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentProduct");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.ProductWebhook", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.Product", "Product")
                        .WithMany("Webhooks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryDiagnostic", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.TelemetryRecord", "Record")
                        .WithOne("DiagnosticData")
                        .HasForeignKey("SoftLicence.Server.Data.TelemetryDiagnostic", "TelemetryRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryDiagnosticPort", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.TelemetryDiagnostic", "Diagnostic")
                        .WithMany("Ports")
                        .HasForeignKey("TelemetryDiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnostic");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryDiagnosticResult", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.TelemetryDiagnostic", "Diagnostic")
                        .WithMany("Results")
                        .HasForeignKey("TelemetryDiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagnostic");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryError", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.TelemetryRecord", "Record")
                        .WithOne("ErrorData")
                        .HasForeignKey("SoftLicence.Server.Data.TelemetryError", "TelemetryRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryEvent", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.TelemetryRecord", "Record")
                        .WithOne("EventData")
                        .HasForeignKey("SoftLicence.Server.Data.TelemetryEvent", "TelemetryRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryRecord", b =>
                {
                    b.HasOne("SoftLicence.Server.Data.Product", "Product")
                        .WithMany("TelemetryRecords")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.AdminRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.License", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.LicenseType", b =>
                {
                    b.Navigation("CustomParams");

                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.Product", b =>
                {
                    b.Navigation("LicenseTypes");

                    b.Navigation("Licenses");

                    b.Navigation("SubProducts");

                    b.Navigation("TelemetryRecords");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryDiagnostic", b =>
                {
                    b.Navigation("Ports");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("SoftLicence.Server.Data.TelemetryRecord", b =>
                {
                    b.Navigation("DiagnosticData");

                    b.Navigation("ErrorData");

                    b.Navigation("EventData");
                });
#pragma warning restore 612, 618
        }
    }
}
